config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    member do
      post :vote
    end
  end

  resources :categories

  resources :comments do
    member do
      post :vote
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories
  before_save :generate_slug

  def to_param
    self.slug
  end

  private

  def generate_slug
    self.slug = self.name.gsub(" ", "-").downcase
  end
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  has_many :votes, as: :voteable
end

app/models/interation_test.rb
class InterationTest < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Sluggable
  sluggable_column :title

  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :comments
  has_many :votes, as: :voteable

  def total_votes
    up_votes - down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end

end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
  before_validation :generate_slug

  private

  def generate_slug
    self.slug = self.name.gsub(" ", "-").downcase
  end

  def to_param
    self.slug
  end  
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voteable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :find_categories

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

  def find_categories
    @categories = Category.all
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :find_category, only: [:show]

  def show
    @posts = @category.posts.includes(:categories)
  end

  private

  def find_category
    @category = Category.where("slug=?", params[:id]).first
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:id])
    @comment = Comment.create(comment_params)
    if @comment.save(@comment)
      redirect_to @post
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :find_post, only: [:show, :vote]

  def index
    @posts = Post.all.includes(:categories).order(id: :desc)
  end

  def show
    @comments = Post.includes(comments: [:user]).where("slug = ?", params[:id]).first
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def vote
    Vote.create(vote: params[:vote], voteable: @post, user_id: current_user.id)
    flash[:notice] = "Your vote was counted."
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def find_post
    @post = Post.where("slug = ?", params[:id]).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_url(email)
    gravatar_email = Digest::MD5.hexdigest(email.downcase)
    return "http://www.gravatar.com/avatar/#{gravatar_email}?s=48"
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_categories.html.erb
<% categories.each do |category| %>
  <span class="badge"><%= link_to category.name, category %></span>
<% end %>

app/views/categories/_category_header.html.erb
<div class="container">
  <h1>
    <%= link_to "All Posts", posts_path %>
    <i class="fa fa-angle-double-right"></i>
    <%= link_to @category.name, @category %>
  </h1>
  <% if user_signed_in?  %>
    <%= link_to "Add Post", new_post_path , class: "btn btn-primary pull-right btn-right-side"%>
  <% else %>
    <br>
  <% end %>
</div>

app/views/categories/show.html.erb
<%= render 'categories/category_header' %>

<div class="container">
  <% @posts.each do |post| %>
    <%= render post%>
  <% end %>
</div><!-- container -->

app/views/comments/_comment.html.erb
<div class="row">

  <div class="col-md-2">
    <div class="well block-vote">
      <a href="#" class="vote-up"><i class="fa fa-arrow-up"></i></a>
      <span class="vote-count">10 votes</span>
      <a href="#" class="vote-down"><i class="fa fa-arrow-down"></i></a>
    </div><!-- well -->
  </div><!-- col-md-1 -->
  <div class="col-md-4">
    <div class="well">
      <div class="post-content">
          <%= sanitize comment.body.gsub(/\n/, '<br/>') %>
      </div><!-- post-content -->
      <p>
        <span class="quiet">posted by</span> <%= link_to comment.user.name , "#" %>
        <small>at 10/30/2015  7:43am PDT</small>
      </p>
    </div><!-- well -->
  </div><!-- col-md-8 -->
</div><!-- row -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TealeafPostit</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "shared/navbar" %>
  <%= yield %>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
</body>
</html>

app/views/posts/_post.html.erb
<div class="row">
  <div class="col-md-2">
    <div class="well block-vote">
      <%= link_to vote_post_path(post, vote: true), method: :post, class: "vote-up" do %>
        <i class="fa fa-arrow-up"></i>
      <% end %>
      <span class="vote-count"><%= post.total_votes %> votes</span>
      <%= link_to vote_post_path(post, vote: false), method: :post, class: "vote-down" do %>
        <i class="fa fa-arrow-down"></i>
      <% end %>
    </div><!-- well -->
  </div><!-- col-md-1 -->
  <div class="col-md-8">
    <div class="well">
      <% post.categories.each do |category| %>
        <span class="badge">
          <%= link_to category.name, category %>
        </span>
      <% end %>
      <h3><%= link_to post.title, post %></h3>
      <div class="post-content">
          <%= sanitize post.content.gsub(/\n/, '<br/>') %>
      </div><!-- post-content -->
      <p>
        <span class="quiet">posted by</span> <%= link_to "Steven", "#" %>
        <small>at 10/30/2015  7:43am PDT</small>
      </p>
      <%= link_to "0 comments", "#" %>
    </div><!-- well -->
  </div><!-- col-md-8 -->
</div><!-- row -->

app/views/posts/index.html.erb
<div class="container">
  <h1>All Posts</h1>
  <% if user_signed_in? %>
    <%= link_to "Add Post", new_post_path , class: "btn btn-primary pull-right btn-right-side"%>
  <% end %>
</div><!-- container -->

<div class="container">
  <% @posts.each do |post| %>
    <%= render post%>
  <% end %>
</div><!-- container -->

app/views/posts/new.html.erb
<div class="conatiner">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Create New Post</h1>

      <%= form_for @post do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div><!-- form-group -->
        <div class="form-group">
          <%= f.label :content %>
          <%= f.text_area :content, class: "form-control", rows: 10 %>
        </div><!-- form-group -->
        <%= f.submit %>
      <% end %>
    </div><!-- col-md-6 col-md-offset-2 -->
</div><!-- row -->
</div><!-- conatiner -->

app/views/posts/show.html.erb
<div class="container">
  <%= render 'categories/categories', categories: @post.categories %>
  <div class="t-margin">
    <h1><%= @post.title %></h1>
    <textarea rows="8" cols="40" disabled>
      <%= @post.content %>
    </textarea>
  </div><!-- post-show -->
  <% @post.comments.each do |comment| %>
    <%= render comment %>
  <% end %>

</div><!-- container -->

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Postit", posts_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="main-navbar">
        <ul class="nav navbar-nav">
          <li><a href="#">Link</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% cache [@categories] do %>
                <% @categories.each do |cate| %>
                  <li><%= link_to cate.name, cate %></li>
                <% end %>
              <% end %>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if !user_signed_in? %>
            <li><%= link_to "Log In", new_user_session_path %></li>
            <li><%= link_to "Register", new_user_registration_path %></li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag gravatar_url("szteven3@gmail.com"), class: "avatar_img" %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Sign in as <%= current_user.name %></a></li>
                <li role="separator" class="divider"></li>
                <li>
                  <%= link_to edit_user_registration_path do %>
                    <i class="fa fa-pencil"></i>Edit Profile
                  <% end %>
                </li>
                <li>
                  <%= link_to "#" do %>
                    <i class="fa fa-user"></i>View Prorile
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } do %>
                    <i class="fa fa-arrow-circle-left"></i>Logout
                  <% end %>
                </li>

              </ul>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>